import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { trpc } from "../utils/trpc";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { registerLocale } from "react-datepicker";
import th from "date-fns/locale/th";
registerLocale("th", th);
import Input from "../components/ui/Input";
import { useEffect, useState } from "react";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

type Stokc = {
  itemgroup: string;
  qty: Number;
};
const Home: NextPage = () => {
  const invStock = trpc.useQuery(["example.groupInvStock"]);
  const [value, onChange] = useState([new Date(), new Date()]);
  const [startDate, setStartDate] = useState(new Date());
  const [endDate, setEndDate] = useState(new Date());
  const [timeDiff, setTimeDiff] = useState(0);
  const [score, setScore] = useState(80);
  const [grade, setGrade] = useState("A");

  const handleScoreChange = (e: number) => {
    if (e >= 80) {
      setGrade("A");
    } else if (e >= 50) {
      setGrade("B");
    } else {
      setGrade("F");
    }
    setScore(e);
  };

  const handleStartDateChange = (date, event) => {
    setStartDate(date);
  };

  const handleEndDateChange = (date, event) => {
    setEndDate(date);
  };

  useEffect(() => {
    return () => {
      startDate.setHours(9);
      startDate.setMinutes(36);
      startDate.setSeconds(12);

      endDate.setHours(10);
      endDate.setMinutes(46);
      endDate.setSeconds(30);
    };
  }, []);

  useEffect(() => {
    return setTimeDiff(
      parseInt(
        (
          Math.abs(endDate.getTime() - startDate.getTime()) /
          (1000 * 60)
        ).toString()
      )
    );
  }, [startDate, endDate]);

  return (
    <>
      <Head>
        <title>ข้อสอบวัดความรู้(สารสนเทศระบบ ERP)</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-xl md:text-[2rem] leading-normal font-extrabold text-gray-700">
          <p>ข้อสอบวัดความรู้(สารสนเทศระบบ ERP)</p>
          <p>QTC Energy Public Company Limited</p>
        </h1>

        <div className="grid gap-5 pt-5 mt-3 md:grid-cols-1 lg:w-2/3">
          <section className="flex flex-col justify-center p-2 lg:p-6 duration-300 border-2 border-gray-500 rounded shadow-xl ">
            <div className="flex flex-col p-2 space-y-2 space-x-2">
              <h2 className="text-sm sm:text-lg text-gray-700 font-semibold">
                1. ระบบ ERP ที่ท่านรู้จักมีอะไรบ้าง จงอย่างตัวอย่าง มาสัก 3
                ตัวอย่าง
              </h2>

              <div className="flex flex-col py-2 font-semibold">
                <p>1. SAP</p>
                <p>2. AS400</p>
                <p>3. Odoo</p>
              </div>
            </div>
          </section>

          <section className="flex flex-col justify-center p-2 lg:p-6 duration-300 border-2 border-gray-500 rounded shadow-xl ">
            <div className="flex flex-col p-2 space-y-2 space-x-2">
              <h2 className="text-sm sm:text-lg text-gray-700 font-semibold">
                2. ระบบ ERP ประกอบด้วย Module อะไรบ้าง และอธิบายการทำาการในแต่ละ
                Module
              </h2>

              <div className="flex flex-col py-2 space-y-3">
                <div>
                  <p className="font-semibold">1. ระบบจัดการทัพยากรบุคล</p>
                  <p>
                    ใช้สำหรับด้านการบริหารงานบุคคล ตั้งแต่การสรรหาพนักงาน
                    การจ่ายเงินเดือน การจัดการฝึกอบรม จัดการข้อมูลการมาทำงาน
                    การขาด ลา มาสาย เพื่อใช้ในการประเมินในการปรับขึ้นเงินเดือน
                    การจ่ายโบนัส
                  </p>
                </div>
                <div>
                  <p className="font-semibold">2. ระบบวางแผนการผลิต</p>
                  <p>
                    เป็นโมดูลที่ใช้จัดการข้อมูลผลิตภัณฑ์สำหรับการการผลิต
                    รวบรวมรายการวัตถุดิบของผลิตภัณฑ์ ใช้กำหนดขั้นตอนการผลิต
                    ใช้วางแผนการผลิตรายวัน รายสัปดาห์
                  </p>
                </div>
                <div>
                  <p className="font-semibold">3. ระบบขาย</p>
                  <p>
                    โมดูลนี้ใช้สำหรับการออกใบเสนอราคาและใบสั่งขาย
                    สามารถกำหนดส่วนลดให้กับกลุ่มลูกค้าหรือเป็นรายลูกค้าได้
                    สามารถออกใบขนสินค้า ออกบิลการขาย และสามารถดูรายการสรุปการขาย
                    การส่งสินค้า และการรับคืนสินค้าได้
                  </p>
                </div>
                <div>
                  <p className="font-semibold">4. ระบบจัดซื้อ</p>
                  <p>
                    โมดูลนี้ใช้สำหรับออกใบขอซื้อ ขอใบเสนอราคา และใบสั่งซื้อ
                    สามารถจัดการข้อมูลของ Supplier สามารถเปรียบเทียบราคาได้
                    จัดเก็บประวัติการสั่งซื้อสินค้า และรางานการส่งสินค้า
                  </p>
                </div>
                <div>
                  <p className="font-semibold">5. ระบบบัญชี</p>
                  <p>
                    ประกอบด้วยระบบต่างต่างๆเกี่ยวกับการจัดการการเงินเช่น
                    ระบบบัญชีเจ้าหนี ระบบสินทรัพย์ถาวร ระบบการทำบัญชีต้นทุน
                    การบริหารเงินสด การบริหารงบประมาณ ระบบบัญชีลูกหนี้
                    รวมไปถึงระบบรายงานผลการดำเนินงานกำไร-ขาดทุน
                  </p>
                </div>
                <div>
                  <p className="font-semibold">6. ระบบคลังสินค้า</p>
                  <p>
                    โมดูลนี้ใช้สำหรับจัดการคลังสินค้า
                    โดยสามารถกำหนดพื้นที่จัดเก็บสิ้นค้าได้หลาย Location
                    สามารถกำหนดMinimum stock
                    เพื่อทำการสั่งสินค้าเข้าคลังสินค้าอัตโนมัติได้
                    สามารถสรุบยอดสินค้า และต้นทุนสินค้าได้
                    สามารถดูรายงานการเคลื่อนไหวของสินค้าของแต่ละรายได้
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section className="flex flex-col justify-center p-2 lg:p-6 duration-300 border-2 border-gray-500 rounded shadow-xl ">
            <div className="flex flex-col p-2 space-y-2 space-x-2">
              <h2 className="text-sm sm:text-lg text-gray-700 font-semibold">
                3. ท่านคิดว่า Module อะไรที่ท่านถนัดมากที่สุด
              </h2>
              <div className="inline-flex py-2 items-center">
                ระบบคลังสินค้า
              </div>
            </div>
          </section>

          <section className="flex flex-col justify-center p-2 lg:p-6 duration-300 border-2 border-gray-500 rounded shadow-xl ">
            <div className="flex flex-col p-2 space-y-2 space-x-2">
              <h2 className="text-sm sm:text-lg text-gray-700 font-semibold">
                4. ให้ทำาการเขียน Data Flow การทำางานของระบบ ERP มาสัก 1 Module
              </h2>
              <div className="flex text-[18px] font-bold pt-4 border-b-2 border-gray-300">
                Flowchart
              </div>
              <div className="pt-4">
                <Image
                  width={48}
                  height={20}
                  className="rounded-lg"
                  src="/images/4.jpg"
                  alt="user-profile"
                  layout="responsive"
                />
              </div>
            </div>
          </section>

          <section className="flex flex-col justify-center p-2 lg:p-6 duration-300 border-2 border-gray-500 rounded shadow-xl ">
            <div className="flex flex-col p-2 space-y-2 space-x-2">
              <h2 className="text-sm sm:text-lg text-gray-700 font-semibold">
                5. จากข้อมูลใน Table ด้านล่าง ดังรูป
              </h2>
              <div className="flex flex-col">
                <div className="pt-4">
                  <Image
                    layout="responsive"
                    src="/images/5.jpg"
                    objectFit="cover"
                    width="300"
                    height="300"
                    className="rounded-lg"
                  />
                </div>
              </div>
              <div className="flex flex-col">
                <div className="flex text-[18px] font-bold pt-4 border-b-2 border-gray-300">
                  Database Design
                </div>
                <div className="pt-4">
                  <Image
                    layout="responsive"
                    src="/images/5_1.jpg"
                    objectFit="cover"
                    width="400"
                    height="200"
                    className="rounded-lg"
                  />
                </div>
              </div>

              <div className="flex flex-col">
                <div className="flex text-[18px] font-bold pt-4 border-b-2 border-gray-300">
                  Code
                </div>
                <div className="pt-4">
                  <Image
                    layout="responsive"
                    src="/images/5_2.jpg"
                    objectFit="cover"
                    width="600"
                    height="200"
                    className="rounded-lg"
                  />
                </div>
              </div>

              <div className="flex text-[18px] font-bold pt-4 border-b-2 border-gray-300">
                Result
              </div>
              <div className="inline-flex py-2 items-center">
                <div className="font-bold text-[18px] lg:text-[20px]">
                  {invStock.data ? (
                    <>
                      <div className="text-center">
                        <div className="grid grid-cols-2 border-2 border-gray-600">
                          <div className="w-24">Group</div>
                          <div className="w-24 border-l-2 border-gray-600">
                            Qty
                          </div>
                        </div>
                        {invStock.data.map((data: Stokc) => {
                          return (
                            <div
                              className="grid grid-cols-2 border-2 border-t-0 border-gray-600"
                              key={data.itemgroup}
                            >
                              <div className="w-24">{data.itemgroup}</div>
                              <div className="w-24 border-l-2 border-gray-600">
                                {Number(data.qty)}
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    </>
                  ) : (
                    <p>Loading..</p>
                  )}
                </div>
              </div>
            </div>
          </section>

          <section className="flex flex-col justify-center p-2 lg:p-6 duration-300 border-2 border-gray-500 rounded shadow-xl ">
            <div className="flex flex-col p-2 space-y-2 space-x-2">
              <h2 className="text-sm sm:text-lg text-gray-700 font-semibold">
                6. จงเขียนโปรแกรมด้วยภาษาที่ท่านคิดว่าถนัดที่สุด
                โดยให้นำเวลาสิ้นสุดลบเวลาเริ่มต้นจะได้กี่นาที โดยกำหนดเวลาดังนี้
                Start Date = 9:36:12 End Date = 10:46:30
              </h2>
              <div className="flex flex-col">
                <div className="flex text-[18px] font-bold pt-4 border-b-2 border-gray-300">
                  Code
                </div>
                <div className="pt-4">
                  <Image
                    layout="responsive"
                    src="/images/6.jpg"
                    objectFit="cover"
                    width="300"
                    height="180"
                    className="rounded-lg"
                  />
                </div>
              </div>

              <div className="flex text-[18px] font-bold pt-4 border-b-2 border-gray-300">
                Result
              </div>
              <div className="inline-flex space-x-2 items-center pt-2">
                <div className="flex text-[16px] lg:text-lg w-20 lg:w-24 font-semibold">
                  Start Date
                </div>
                <div className="flex">
                  <DatePicker
                    selected={startDate}
                    showTimeSelect
                    onChange={handleStartDateChange}
                    dateFormat="MM/dd/yyyy HH:mm:ss"
                    locale="th"
                    className="bg-indigo-500 text-white rounded-lg px-2 py-1"
                  />
                </div>
              </div>

              <div className="inline-flex space-x-2 items-center">
                <div className="flex text-[16px] lg:text-lg w-20 lg:w-24 font-semibold">
                  End Date
                </div>
                <div className="flex">
                  <DatePicker
                    selected={endDate}
                    showTimeSelect
                    onChange={handleEndDateChange}
                    dateFormat="MM/dd/yyyy HH:mm:ss"
                    locale="th"
                    className="bg-indigo-500 text-white rounded-lg px-2 py-1"
                  />
                </div>
              </div>
              <div className="inline-flex py-2 items-center">
                <div className="font-bold text-[18px] lg:text-[20px]">
                  Time Diff(Mins) {timeDiff}
                </div>
              </div>
            </div>
          </section>

          <section className="flex flex-col justify-center p-2 lg:p-6 duration-300 border-2 border-gray-500 rounded shadow-xl ">
            <div className="flex flex-col p-2 space-y-2 space-x-2">
              <h2 className="text-sm sm:text-lg text-gray-700 font-semibold pb-4">
                <div>
                  <p>
                    7. จงเขียน Data Flow
                    และโปรแกรมด้วยภาษาที่ท่านคิดว่าถนัดที่สุด
                  </p>
                </div>
                <div className="flex flex-cols-2">
                  <div className="w-36">โดยกำหนด</div>
                  <div>
                    <p>1. คะแนน มากกว่าหรือเท่ากับ 80 แสดงเกรด A</p>
                    <p>
                      2. คะแนน น้อยกว่า 80 แต่มากว่าหรือเท่ากับ 50 แสดงเกรด B
                    </p>
                    <p>3. น้อยกว่า 50 แสดงเกรด F</p>
                  </div>
                </div>
              </h2>
              <div className="flex flex-col w-full h-auto">
                <div className="flex text-[18px] font-bold pt-4 border-b-2 border-gray-300">
                  Flowchart
                </div>
                <div className="pt-4">
                  <Image
                    width={48}
                    height={48}
                    className="rounded-lg"
                    src="/images/7.jpg"
                    alt="user-profile"
                    layout="responsive"
                  />
                </div>
              </div>

              <div className="flex flex-col w-full h-auto">
                <div className="flex text-[18px] font-bold pt-4 border-b-2 border-gray-300">
                  Code
                </div>
                <div className="pt-4">
                  <Image
                    width={48}
                    height={20}
                    className="rounded-lg"
                    src="/images/7_1.jpg"
                    alt="user-profile"
                    layout="responsive"
                  />
                </div>
              </div>

              <div className="flex text-[18px] font-bold pt-4 border-b-2 border-gray-300">
                Result
              </div>
              <div className="inline-flex space-x-2 items-center pt-4">
                <div className="text-[18px] font-bold">Score</div>
                <Input
                  type="number"
                  value={score}
                  onChange={(e) => handleScoreChange(parseInt(e))}
                  className="rounded-lg"
                />
              </div>

              <div className="inline-flex py-2 items-center">
                <div className="font-bold text-[18px] lg:text-[20px]">
                  Your Grade is {grade}
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </>
  );
};

export default Home;
